baseURL: "https://atsip-ru.github.io/"
title: "atsip.ru - телефонные решения на базе АТС Asterisk"
languageCode: "ru"
pagination.pagerSize: 3
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: AtSIP
  description: "Решения телефонии на базе открытой платформы IP-телефонии Asterisk; Оборудование для создания телефонных систем VoIP; Типовые и оригинальные способы реализации телефонных решений, способы модернизации телефонии организаций и УАТС; Варианты и методы экономии на междугородних переговорах;"
  keywords: [SIP, Asterisk, IT, Orsk, Orenburg, Орск, Оренбург, IP-Telephony, IP-телефония]
  author: ["Dmitriy Q"]
  # author: ["Me", "You"] # multiple authors
  images: ["/logo.png"]
  DateFormat: "2 January 2006"
  languageAltTitle: "Russian"
  defaultTheme: light # dark, light
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: true
  ShareButtons: ["telegram", "twitter"]
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
#  disableAnchoredHeadings: true
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon/favicon.svg"
    favicon16x16: "/favicon/favicon-16x16.png"
    favicon32x32: "/favicon/favicon-32x32.png"
    apple_touch_icon: "/favicon/apple-touch-icon.png"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: " "
    icon: /logo.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: AtSIP
    subtitle: "Телефонные решения на базе АТС Asterisk"
    imageUrl: "/logo.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Посты
        url: posts
      - name: Теги
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "SIP-привет \U0001F44B"
    Content: Телефонные решения на базе АТС Asterisk

  socialIcons:
    - name: telegram
      url: "https://t.me/intelcom56"
    - name: github
      url: "https://github.com/atsip-ru"
    - name: phone
      url: "tel:+79058994494"

  analytics:
#    google:
#      SiteVerificationTag: "XYZabc"
#    bing:
#      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "a654f52a611b9bb6"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

#  editPost:
#    URL: "https://github.com/atsip-ru/atsip-ru.github.io/tree/master/content"
#    Text: "Внесите изменения" # edit text
#    appendFilePath: false # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: articles
      name: Статьи
      url: /articles/
      title: Статьи
      weight: 10
    - identifier: instructions
      name: Инструкции
      url: /instructions/
      title: Инструкции
      weight: 20
    - identifier: about
      name: О нас
      url: /about/
      weight: 30
    - identifier: tags
      name: Теги
      url: /tags/
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
